### route of the api server
GET http://localhost:3010/ HTTP/1.1


### Get all menu items
GET http://localhost:3010/menu/ HTTP/1.1


### get menu item by id
GET http://localhost:3010/menu/1 HTTP/1.1


### get menu item of the day -- for home screen
GET http://localhost:3010/menu/oftheday HTTP/1.1


### create menu item
POST http://localhost:3010/menu HTTP/1.1
content-type: application/json

{
            "title": 'menu item 1',
			"description": 'menu item decription',
			"deliversOn": 2020-07-15,
			"orderStarts": 2020-07-12,
			"orderEnds": 2020-07-15,
			"maxOrders": 20,
			"cost": 1500
}


### update menu item by id
PUT http://localhost:3010/menu/1 HTTP/1.1
content-type: application/json

{
    "name": "sample menu item",
    "message": "Hello menu"
}


### delete menu item by id
DELETE  http://localhost:3010/menu/1 HTTP/1.1
content-type: application/json

{
    "name": "sample menu item",
    "message": "Hello menu"
}