### logout current user session
GET http://localhost:3010/logout HTTP/1.1
### get current logged in user
GET http://localhost:3010/user HTTP/1.1

### Register Store Admin
POST http://localhost:3010/register HTTP/1.1
content-type: application/json

{
  "username": "hungry5",
  "email":"hungry@email.com",
  "password":"feedme1",
  "role": "seller"
}


### Register Customer
POST http://localhost:3010/register HTTP/1.1
content-type: application/json

{
  "username": "foody",
  "email":"customfoodyer@email.com",
  "password":"1234",
  "role": "buyer"
}

### Login Store Admin
POST http://localhost:3010/login HTTP/1.1
content-type: application/json

{
  "username": "hungry5",
  "password":"feedme1"
}



### Login Customer
POST http://localhost:3010/login HTTP/1.1
content-type: application/json

{
  "username": "customer5",
  "password":"somenice-pw"
}